### PR TITLE
update edit-project-key ngModel need name attr error

### PR DESCRIPTION
**Pull request by tqcenglish**
#60

### CODE REVIEW

**Comment by anthonynsimon** [comment]
Hi, thanks for the contribution! Could you please reference an issue or create one related to these changes?

**Comment by anthonynsimon** [comment]
Looks good, normally you would open a Pull Request per issue, and not all together. But it's ok.

Before I merge into the master branch, can you please set the default language to English? So it stays the same as before for other users:

```typescript
  constructor(private router: Router, translate: TranslateService) {
    translate.setDefaultLang('en-US');
  }
```

Thanks a lot!

**Comment by anthonynsimon** [comment]
And please also set back the `apiUrl` to `https://localhost/api/v1` so that it doesn't break the config for previous users :)

**Comment by tqcenglish** [comment]
hi, I have return original `apiUrl` setting. 
 a lot `translate` had add  in *.html file and  create  language select on login page.

**Comment by anthonynsimon** [comment]
Looks good!

**Pull request merged**
