### PR TITLE
You don't need to be root to build the web application

### PR DESCRIPTION
**Pull request by lght**
I was having a quick look at your software, and realized you were trying to install something as root on my machine.

Since you are already requiring a version of `angular-cli` in package requirements, you don't have to install with `-g`

### CODE REVIEW

**Comment by anthonynsimon** [comment]
Ok good point, but wouldn't this break the web app build?

Even after adding the build script to the `package.json`, it still fails:

```
# package.json
...
  "scripts": {
    "start": "ng serve",
    "build": "ng build -prod",
...
```
And then to run
```
$ npm run build

> parrot@0.0.0 build /Users/anthony/dev/go/src/github.com/anthonynsimon/parrot/web-app
> ng build -prod

Error: EACCES: permission denied, unlink '/Users/anthony/dev/go/src/github.com/anthonynsimon/parrot/web-app/dist/009fb12d830bb9b28859fc0ce2585243.svg'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
...
```

**Comment by lght** [comment]
Hey, that would be because you originally created those files as root user. On a fresh installation, you won't have this issue.

**Comment by iilei** [comment]
👍 for filing this PR - @anthonynsimon you probably need to revise your npm config so it installs global packages without root. [Like described here](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md), or alternatively by using [nvm](https://github.com/creationix/nvm)

**Comment by anthonynsimon** [comment]
@iilei Thanks!

@lght ok so I was checking out your PR. I think there is only one thing left to do for it to work properly:

1) The `web-app/scripts/build.sh` scripts needs to run the `npm run build` command instead of the `ng build -prod` which was installed globally. That part should look like the following:

```
...
    echo "Building web app..." && \
    npm run build && \
    echo 0
...
```

And the `web-app/package.json` should now have a `build` task (npm script):
```
...
  "scripts": {
    "build": "ng build -prod",
...
```

I tried it quickly without having ng installed globally and it works. Let me know on your side.

**Pull request closed without merging**
